[package]
name = "flutter_rust_bridge_example"
version = "1.0.0"
edition = "2018"

[lib]
name = "flutter_rust_bridge_example"
crate-type = ["cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = { path = "../../../frb_codegen" }

[dependencies]
anyhow = { version = "1.0.58", features = ["backtrace"] }
flutter_rust_bridge = { path = "../../../frb_rust" }
lazy_static = "1.4.0"

[dependencies.external-lib] # used for demo of external types mirroring
path = "./external"
package = "flutter_rust_bridge_example_external"
